// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkCLLIkddHJA7HeBP9BN4gsF5UwkcF9F8',
    appId: '1:593751001048:web:8fddab547c72f580b3d4ad',
    messagingSenderId: '593751001048',
    projectId: 'flutter-projects-412e6',
    authDomain: 'flutter-projects-412e6.firebaseapp.com',
    storageBucket: 'flutter-projects-412e6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZTAbG6ux1OEvs6XlL_t3WVvYxsIjKUi8',
    appId: '1:593751001048:android:a27f62d6ae7f3a74b3d4ad',
    messagingSenderId: '593751001048',
    projectId: 'flutter-projects-412e6',
    storageBucket: 'flutter-projects-412e6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCDmgenTStamJNZJnP6esHpSPoIc2_Hg',
    appId: '1:593751001048:ios:57fec4ac6c6c5f0eb3d4ad',
    messagingSenderId: '593751001048',
    projectId: 'flutter-projects-412e6',
    storageBucket: 'flutter-projects-412e6.firebasestorage.app',
    iosBundleId: 'com.jorge.pushapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCDmgenTStamJNZJnP6esHpSPoIc2_Hg',
    appId: '1:593751001048:ios:f3fca8521420b026b3d4ad',
    messagingSenderId: '593751001048',
    projectId: 'flutter-projects-412e6',
    storageBucket: 'flutter-projects-412e6.firebasestorage.app',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBkCLLIkddHJA7HeBP9BN4gsF5UwkcF9F8',
    appId: '1:593751001048:web:5e439056e716f313b3d4ad',
    messagingSenderId: '593751001048',
    projectId: 'flutter-projects-412e6',
    authDomain: 'flutter-projects-412e6.firebaseapp.com',
    storageBucket: 'flutter-projects-412e6.firebasestorage.app',
  );
}
